# Site settings
title: Scott Stewart
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  shite
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scottstewart.co" # the base hostname & protocol for your site
twitter_username: sirscottstewart
github_username:  scottianstewart

# Build settings
markdown: kramdown

port: 3000


